/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupohabilitacionlllm.proyecto.vial.gchu.srl.View;
import grupohabilitacionlllm.proyecto.vial.gchu.srl.Controladores.ControladorEmpleado;
import grupohabilitacionlllm.proyecto.vial.gchu.srl.Controladores.ControladorMaquinaria;
import grupohabilitacionlllm.proyecto.vial.gchu.srl.Controladores.ControladorProyecto;
/**
 *
 * @author lucia
 */
public class AdminView extends javax.swing.JFrame {
ControladorEmpleado controladorEmpleado = new ControladorEmpleado();
ControladorMaquinaria controladorMaquinaria = new ControladorMaquinaria();
ControladorProyecto controladorProyecto = new ControladorProyecto();
    /**
     * Creates new form main
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empleadoDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        gestionDeEmpleadosLabel = new javax.swing.JLabel();
        cerrarEmpleadoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        empleadosTable = new javax.swing.JTable();
        empleadoMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jAltaItem = new javax.swing.JMenuItem();
        BajaItem = new javax.swing.JMenuItem();
        modificarItem = new javax.swing.JMenuItem();
        altaEmpleadoDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        apellidoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        fechanacLabel = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        dniFormattedTextField = new javax.swing.JFormattedTextField();
        fechanacFormattedTextField = new javax.swing.JFormattedTextField();
        aceptaraltaButton = new javax.swing.JButton();
        cancelaraltaButton = new javax.swing.JButton();
        altaDeEmpleadosLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        modificarEmpleadoDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        modificarEmpleadosLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        empleadoList1 = new javax.swing.JList<>();
        cancelarmodificarButton = new javax.swing.JButton();
        aceptarModificarButton = new javax.swing.JButton();
        apellidoLabel1 = new javax.swing.JLabel();
        nombreLabel1 = new javax.swing.JLabel();
        dniLabel1 = new javax.swing.JLabel();
        telLabel1 = new javax.swing.JLabel();
        direccionLabel1 = new javax.swing.JLabel();
        fechanacLabel1 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        apellidoTextField1 = new javax.swing.JTextField();
        dniFormattedTextField1 = new javax.swing.JFormattedTextField();
        nombreTextField1 = new javax.swing.JTextField();
        telfTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        fechanacFormattedTextField1 = new javax.swing.JFormattedTextField();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        bajaEmpleadoDialog = new javax.swing.JDialog();
        bajaEmpleadoButton = new javax.swing.JButton();
        cancelarBajaEmpleadoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bajaDeEmpleadosLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        empleadosList = new javax.swing.JList<>();
        ropaTrabajoDialog = new javax.swing.JDialog();
        ropaComboBox = new javax.swing.JComboBox<>();
        talleComboBox = new javax.swing.JComboBox<>();
        selecRopaLabel = new javax.swing.JLabel();
        selecTalleLabel = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ropaTrabajoTable = new javax.swing.JTable();
        ropaDeTrabajoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        elementoSeguridadDialog = new javax.swing.JDialog();
        selecElemSegLabel = new javax.swing.JLabel();
        elementoSeguridadComboBox = new javax.swing.JComboBox<>();
        cancelarButton2 = new javax.swing.JButton();
        guardarButton1 = new javax.swing.JButton();
        altaDeEmpleadosLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        elementoSeguridadTable = new javax.swing.JTable();
        fechaEntregaESFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        fechaDevolucionESFormattedTextField1 = new javax.swing.JFormattedTextField();
        proyectoDialog = new javax.swing.JDialog();
        altaDeEmpleadosLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        proyectoMenuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        altaProyectoDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        altaDeEmpleadosLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        mainsalirButton = new javax.swing.JButton();
        empleadoButton = new javax.swing.JButton();
        proyectoButton = new javax.swing.JButton();
        maquinariaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(930, 760));

        gestionDeEmpleadosLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        gestionDeEmpleadosLabel.setText("Gestión de Empleados");

        cerrarEmpleadoButton.setText("Cerrar");
        cerrarEmpleadoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarEmpleadoButtonMouseClicked(evt);
            }
        });

        empleadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "DNI", "Dirección", "Teléfono", "Fecha de Nacimiento", "Estado", "Especialización", "Tipo", "Fecha de Modificación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empleadosTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(empleadosTable);
        empleadosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(gestionDeEmpleadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrarEmpleadoButton)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(gestionDeEmpleadosLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cerrarEmpleadoButton)
                .addGap(19, 19, 19))
        );

        jMenu1.setText("Opciones");

        jAltaItem.setText("Agregar empleado");
        jAltaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaEmpleadoItemMouseClicked(evt);
            }
        });
        jAltaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaItemActionPerformed(evt);
            }
        });
        jMenu1.add(jAltaItem);

        BajaItem.setText("Dar de baja empleado");
        BajaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BajaItemMouseClicked(evt);
            }
        });
        jMenu1.add(BajaItem);

        modificarItem.setText("Modificar empleado");
        modificarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarItemMouseClicked(evt);
            }
        });
        modificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarItemActionPerformed(evt);
            }
        });
        jMenu1.add(modificarItem);

        empleadoMenuBar.add(jMenu1);

        empleadoDialog.setJMenuBar(empleadoMenuBar);

        javax.swing.GroupLayout empleadoDialogLayout = new javax.swing.GroupLayout(empleadoDialog.getContentPane());
        empleadoDialog.getContentPane().setLayout(empleadoDialogLayout);
        empleadoDialogLayout.setHorizontalGroup(
            empleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadoDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        empleadoDialogLayout.setVerticalGroup(
            empleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadoDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        apellidoLabel.setText("Apellido");

        nombreLabel.setText("Nombre");

        dniLabel.setText("DNI");

        telLabel.setText("Teléfono");

        direccionLabel.setText("Dirección");

        fechanacLabel.setText("Fecha de Nacimiento");

        apellidoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTextFieldActionPerformed(evt);
            }
        });

        jTextField5.setText("Calle Número Piso");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        dniFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        fechanacFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        aceptaraltaButton.setText("Aceptar");
        aceptaraltaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptaraltaButtonMouseClicked(evt);
            }
        });

        cancelaraltaButton.setText("Cancelar");
        cancelaraltaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelaraltaButtonMouseClicked(evt);
            }
        });

        altaDeEmpleadosLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        altaDeEmpleadosLabel.setText("Alta de Empleado");

        jLabel3.setText("Especialización");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Rol");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cancelaraltaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptaraltaButton)
                        .addGap(131, 131, 131))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dniFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(apellidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altaDeEmpleadosLabel)
                    .addComponent(nombreLabel)
                    .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fechanacLabel)
                        .addGap(51, 51, 51)
                        .addComponent(fechanacFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altaDeEmpleadosLabel)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniLabel))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechanacLabel)
                    .addComponent(fechanacFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptaraltaButton)
                    .addComponent(cancelaraltaButton))
                .addGap(24, 24, 24))
        );

        jMenu2.setText("Asignar");

        jMenuItem2.setText("Ropa de trabajo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Elemento de seguridad");
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        altaEmpleadoDialog.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout altaEmpleadoDialogLayout = new javax.swing.GroupLayout(altaEmpleadoDialog.getContentPane());
        altaEmpleadoDialog.getContentPane().setLayout(altaEmpleadoDialogLayout);
        altaEmpleadoDialogLayout.setHorizontalGroup(
            altaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        altaEmpleadoDialogLayout.setVerticalGroup(
            altaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaEmpleadoDialogLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setText("Seleccione un empleado");

        modificarEmpleadosLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        modificarEmpleadosLabel.setText("Modificar Empleado");

        empleadoList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        empleadoList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadoList1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(empleadoList1);

        cancelarmodificarButton.setText("Cancelar");
        cancelarmodificarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarmodificarButtonMouseClicked(evt);
            }
        });

        aceptarModificarButton.setText("Aceptar");
        aceptarModificarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarModificarButtonMouseClicked(evt);
            }
        });

        apellidoLabel1.setText("Apellido");

        nombreLabel1.setText("Nombre");

        dniLabel1.setText("DNI");

        telLabel1.setText("Teléfono");

        direccionLabel1.setText("Dirección");

        fechanacLabel1.setText("Fecha de Nacimiento");

        jTextField7.setText("Calle Número Piso");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        apellidoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTextField1ActionPerformed(evt);
            }
        });

        dniFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        jLabel10.setText("Especialización");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Rol");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        fechanacFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(modificarEmpleadosLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fechanacLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(fechanacFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(telLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(direccionLabel1)
                                                .addComponent(nombreLabel1))
                                            .addComponent(dniLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(apellidoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dniFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apellidoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cancelarmodificarButton)
                                        .addGap(155, 155, 155)
                                        .addComponent(aceptarModificarButton))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(modificarEmpleadosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dniLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dniFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel1)
                    .addComponent(telfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechanacFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechanacLabel1))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarmodificarButton)
                    .addComponent(aceptarModificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu3.setText("Asignar");

        jMenuItem4.setText("Ropa de Trabajo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Elemento de Seguridad");
        jMenu3.add(jMenuItem5);

        jMenuBar3.add(jMenu3);

        modificarEmpleadoDialog.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout modificarEmpleadoDialogLayout = new javax.swing.GroupLayout(modificarEmpleadoDialog.getContentPane());
        modificarEmpleadoDialog.getContentPane().setLayout(modificarEmpleadoDialogLayout);
        modificarEmpleadoDialogLayout.setHorizontalGroup(
            modificarEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modificarEmpleadoDialogLayout.setVerticalGroup(
            modificarEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bajaEmpleadoButton.setText("Dar de baja");
        bajaEmpleadoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajaEmpleadoButtonMouseClicked(evt);
            }
        });
        bajaEmpleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaEmpleadoButtonActionPerformed(evt);
            }
        });

        cancelarBajaEmpleadoButton.setText("Cancelar");
        cancelarBajaEmpleadoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarBajaEmpleadoButtonMouseClicked(evt);
            }
        });
        cancelarBajaEmpleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBajaEmpleadoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un empleado");

        bajaDeEmpleadosLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bajaDeEmpleadosLabel.setText("Baja de Empleado");

        empleadosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        empleadosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(empleadosList);

        javax.swing.GroupLayout bajaEmpleadoDialogLayout = new javax.swing.GroupLayout(bajaEmpleadoDialog.getContentPane());
        bajaEmpleadoDialog.getContentPane().setLayout(bajaEmpleadoDialogLayout);
        bajaEmpleadoDialogLayout.setHorizontalGroup(
            bajaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaEmpleadoDialogLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(cancelarBajaEmpleadoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(bajaEmpleadoButton)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bajaEmpleadoDialogLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(bajaDeEmpleadosLabel)
                .addGap(73, 73, 73))
            .addGroup(bajaEmpleadoDialogLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bajaEmpleadoDialogLayout.setVerticalGroup(
            bajaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaEmpleadoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bajaDeEmpleadosLabel)
                .addGroup(bajaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bajaEmpleadoDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(bajaEmpleadoDialogLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(bajaEmpleadoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBajaEmpleadoButton)
                    .addComponent(bajaEmpleadoButton))
                .addGap(27, 27, 27))
        );

        ropaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        talleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selecRopaLabel.setText("Seleccione la ropa");

        selecTalleLabel.setText("Seleccione el talle");

        cancelarButton.setText("Cancelar");

        aceptarButton.setText("Aceptar");

        ropaTrabajoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ropa de Trabajo", "Talle", "Fecha de Entrega", "Fecha de Vencimiento"
            }
        ));
        jScrollPane3.setViewportView(ropaTrabajoTable);

        ropaDeTrabajoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ropaDeTrabajoLabel.setText("Gestión de Ropa de Trabajo");

        jLabel6.setText("Fecha de Entrega");

        jLabel7.setText("Fecha de Vencimiento");

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ropaTrabajoDialogLayout = new javax.swing.GroupLayout(ropaTrabajoDialog.getContentPane());
        ropaTrabajoDialog.getContentPane().setLayout(ropaTrabajoDialogLayout);
        ropaTrabajoDialogLayout.setHorizontalGroup(
            ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ropaTrabajoDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ropaTrabajoDialogLayout.createSequentialGroup()
                        .addComponent(cancelarButton)
                        .addGap(144, 144, 144)
                        .addComponent(aceptarButton)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ropaTrabajoDialogLayout.createSequentialGroup()
                        .addComponent(ropaDeTrabajoLabel)
                        .addGap(78, 78, 78))))
            .addGroup(ropaTrabajoDialogLayout.createSequentialGroup()
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ropaTrabajoDialogLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecRopaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecTalleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ropaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(talleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ropaTrabajoDialogLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        ropaTrabajoDialogLayout.setVerticalGroup(
            ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ropaTrabajoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ropaDeTrabajoLabel)
                .addGap(35, 35, 35)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecRopaLabel)
                    .addComponent(ropaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecTalleLabel)
                    .addComponent(talleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(ropaTrabajoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(aceptarButton))
                .addGap(47, 47, 47))
        );

        selecElemSegLabel.setText("Seleccione el elementod de seguridad");

        elementoSeguridadComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelarButton2.setText("Cancelar");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        guardarButton1.setText("Aceptar");
        guardarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButton1ActionPerformed(evt);
            }
        });

        altaDeEmpleadosLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        altaDeEmpleadosLabel1.setText("Elementos de seguridad");

        jLabel4.setText("Fecha de Entrega");

        elementoSeguridadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Elemento de Seguridad", "F. Entrega", "F. Devolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(elementoSeguridadTable);

        fechaEntregaESFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel5.setText("Fecha de Vencimiento");

        fechaDevolucionESFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout elementoSeguridadDialogLayout = new javax.swing.GroupLayout(elementoSeguridadDialog.getContentPane());
        elementoSeguridadDialog.getContentPane().setLayout(elementoSeguridadDialogLayout);
        elementoSeguridadDialogLayout.setHorizontalGroup(
            elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(cancelarButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarButton1)
                .addGap(135, 135, 135))
            .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecElemSegLabel)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(64, 64, 64)
                .addGroup(elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(elementoSeguridadComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaEntregaESFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaDevolucionESFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(altaDeEmpleadosLabel1)
                .addGap(20, 100, Short.MAX_VALUE))
            .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        elementoSeguridadDialogLayout.setVerticalGroup(
            elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                .addComponent(altaDeEmpleadosLabel1)
                .addGap(18, 18, 18)
                .addGroup(elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementoSeguridadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecElemSegLabel))
                .addGroup(elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elementoSeguridadDialogLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elementoSeguridadDialogLayout.createSequentialGroup()
                        .addComponent(fechaEntregaESFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechaDevolucionESFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(elementoSeguridadDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton2)
                    .addComponent(guardarButton1))
                .addGap(16, 16, 16))
        );

        altaDeEmpleadosLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        altaDeEmpleadosLabel2.setText("Gestión de Proyectos");

        jToggleButton1.setText("Cerrar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha de Inicio", "Fecha Estimada", "Estado", "Nombe", "Fecha de Fin", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable1);

        jMenu4.setText("Opciones");

        jMenuItem1.setText("Crear proyecto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem6.setText("Editar proyecto");
        jMenu4.add(jMenuItem6);

        proyectoMenuBar.add(jMenu4);

        proyectoDialog.setJMenuBar(proyectoMenuBar);

        javax.swing.GroupLayout proyectoDialogLayout = new javax.swing.GroupLayout(proyectoDialog.getContentPane());
        proyectoDialog.getContentPane().setLayout(proyectoDialogLayout);
        proyectoDialogLayout.setHorizontalGroup(
            proyectoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proyectoDialogLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(altaDeEmpleadosLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proyectoDialogLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(proyectoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proyectoDialogLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proyectoDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        proyectoDialogLayout.setVerticalGroup(
            proyectoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proyectoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altaDeEmpleadosLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18))
        );

        altaDeEmpleadosLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        altaDeEmpleadosLabel3.setText("Alta de Empleado");

        jLabel12.setText("Fecha de inicio");

        jLabel13.setText("Fecha estimada de fin");

        jLabel14.setText("Estado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(altaDeEmpleadosLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(altaDeEmpleadosLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(569, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout altaProyectoDialogLayout = new javax.swing.GroupLayout(altaProyectoDialog.getContentPane());
        altaProyectoDialog.getContentPane().setLayout(altaProyectoDialogLayout);
        altaProyectoDialogLayout.setHorizontalGroup(
            altaProyectoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        altaProyectoDialogLayout.setVerticalGroup(
            altaProyectoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainTitle.setText("VIAL Gualeguaychú SRL");

        mainsalirButton.setText("Salir");
        mainsalirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainsalirButtonMouseClicked(evt);
            }
        });

        empleadoButton.setText("Gestionar Empleados");
        empleadoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadoButtonMouseClicked(evt);
            }
        });
        empleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoButtonActionPerformed(evt);
            }
        });

        proyectoButton.setText("Gestionar Proyectos");
        proyectoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proyectoButtonMouseClicked(evt);
            }
        });

        maquinariaButton.setText("Gestionar Maquinaria");
        maquinariaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maquinariaButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("imagen linda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainsalirButton)
                    .addComponent(mainTitle))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maquinariaButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proyectoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(empleadoButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTitle)
                .addGap(72, 72, 72)
                .addComponent(empleadoButton)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(proyectoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(maquinariaButton)
                .addGap(70, 70, 70)
                .addComponent(mainsalirButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoButtonActionPerformed

    private void jAltaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAltaItemActionPerformed

    private void modificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarItemActionPerformed

    private void apellidoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTextFieldActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void bajaEmpleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaEmpleadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaEmpleadoButtonActionPerformed

    private void cancelarBajaEmpleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBajaEmpleadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBajaEmpleadoButtonActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void guardarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarButton1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void empleadoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadoButtonMouseClicked
        empleadoDialog.setVisible(true);
        empleadoDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_empleadoButtonMouseClicked

    private void bajaEmpleadoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajaEmpleadoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaEmpleadoButtonMouseClicked

    private void cancelarBajaEmpleadoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBajaEmpleadoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBajaEmpleadoButtonMouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void apellidoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTextField1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void empleadoList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadoList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadoList1MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void altaEmpleadoItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaEmpleadoItemMouseClicked
        altaEmpleadoDialog.setVisible(true);
        altaEmpleadoDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_altaEmpleadoItemMouseClicked

    private void BajaItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BajaItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BajaItemMouseClicked

    private void modificarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarItemMouseClicked

    private void cancelaraltaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelaraltaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelaraltaButtonMouseClicked

    private void aceptaraltaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptaraltaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptaraltaButtonMouseClicked

    private void cancelarmodificarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarmodificarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarmodificarButtonMouseClicked

    private void aceptarModificarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarModificarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarModificarButtonMouseClicked

    private void mainsalirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainsalirButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainsalirButtonMouseClicked

    private void proyectoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proyectoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_proyectoButtonMouseClicked

    private void maquinariaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maquinariaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maquinariaButtonMouseClicked

    private void cerrarEmpleadoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarEmpleadoButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarEmpleadoButtonMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BajaItem;
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton aceptarModificarButton;
    private javax.swing.JButton aceptaraltaButton;
    private javax.swing.JLabel altaDeEmpleadosLabel;
    private javax.swing.JLabel altaDeEmpleadosLabel1;
    private javax.swing.JLabel altaDeEmpleadosLabel2;
    private javax.swing.JLabel altaDeEmpleadosLabel3;
    private javax.swing.JDialog altaEmpleadoDialog;
    private javax.swing.JDialog altaProyectoDialog;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel apellidoLabel1;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JTextField apellidoTextField1;
    private javax.swing.JLabel bajaDeEmpleadosLabel;
    private javax.swing.JButton bajaEmpleadoButton;
    private javax.swing.JDialog bajaEmpleadoDialog;
    private javax.swing.JButton cancelarBajaEmpleadoButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JButton cancelaraltaButton;
    private javax.swing.JButton cancelarmodificarButton;
    private javax.swing.JButton cerrarEmpleadoButton;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JLabel direccionLabel1;
    private javax.swing.JFormattedTextField dniFormattedTextField;
    private javax.swing.JFormattedTextField dniFormattedTextField1;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JLabel dniLabel1;
    private javax.swing.JComboBox<String> elementoSeguridadComboBox;
    private javax.swing.JDialog elementoSeguridadDialog;
    private javax.swing.JTable elementoSeguridadTable;
    private javax.swing.JButton empleadoButton;
    private javax.swing.JDialog empleadoDialog;
    private javax.swing.JList<String> empleadoList1;
    private javax.swing.JMenuBar empleadoMenuBar;
    private javax.swing.JList<String> empleadosList;
    private javax.swing.JTable empleadosTable;
    private javax.swing.JFormattedTextField fechaDevolucionESFormattedTextField1;
    private javax.swing.JFormattedTextField fechaEntregaESFormattedTextField;
    private javax.swing.JFormattedTextField fechanacFormattedTextField;
    private javax.swing.JFormattedTextField fechanacFormattedTextField1;
    private javax.swing.JLabel fechanacLabel;
    private javax.swing.JLabel fechanacLabel1;
    private javax.swing.JLabel gestionDeEmpleadosLabel;
    private javax.swing.JButton guardarButton1;
    private javax.swing.JMenuItem jAltaItem;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton mainsalirButton;
    private javax.swing.JButton maquinariaButton;
    private javax.swing.JDialog modificarEmpleadoDialog;
    private javax.swing.JLabel modificarEmpleadosLabel;
    private javax.swing.JMenuItem modificarItem;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JButton proyectoButton;
    private javax.swing.JDialog proyectoDialog;
    private javax.swing.JMenuBar proyectoMenuBar;
    private javax.swing.JComboBox<String> ropaComboBox;
    private javax.swing.JLabel ropaDeTrabajoLabel;
    private javax.swing.JDialog ropaTrabajoDialog;
    private javax.swing.JTable ropaTrabajoTable;
    private javax.swing.JLabel selecElemSegLabel;
    private javax.swing.JLabel selecRopaLabel;
    private javax.swing.JLabel selecTalleLabel;
    private javax.swing.JComboBox<String> talleComboBox;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel telLabel1;
    private javax.swing.JTextField telfTextField;
    // End of variables declaration//GEN-END:variables
}
